apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      volumes:
        - name: local
          emptyDir: {}
      containers:
        - name: server
          image: docker.io/dkimot/jumprope-webserver
          env:
          - name: SITE_NAME
            value: 'calvinarts.co'
          - name: REPO_QUANT
            value: '2'
          - name: REPO_0_LOCAL
            value: '/tmp/repos/data'
          - name: REPO_0_REMOTE
            value: 'https://www.github.com/dkimot/fcbdata'
          - name: REPO_1_LOCAL
            value: '/tmp/repos/pagekit'
          - name: REPO_1_LOCAL
            value: 'https://www.github.com/dkimot/pagekit'
          - name: NODE_ENV
            value: 'production'
          - name: SUBSCRIBER_PORT
            value: '5000'
